### ISSUE TITLE
Missing include directories for nlohmann_json and assimp

### ISSUE THREAD

**Issue by FarzanehBakhshaei** [Lachei/VulkanPBRT#28]
When I tried to compile the master, I faced some compilation errors that I fixed with these changes:

[mychanges.patch.txt](https://github.com/Lachei/VulkanPBRT/files/7776993/mychanges.patch.txt)

The issues were:
- include directory for nlohmann_json was missing
- assimp was not included and linked
- vsgXchange::openexr was missing implementation.

**Comment by Lachei** [comment]
> - include directory for nlohmann_json was missing
> - assimp was not included and linked

Both of these should be already linked for in `external/vsgXchange/src/assimp/build_vars.cmake`.
For me it looks like cmake did not find assimp 5.0. If that is the case then neither assimp nor nlohmann_json is being linked.
Pls check which version is being found by letting you print out the `assimp_VERSION`.

> - vsgXchange::openexr was missing implementation.

Here i found an error when openexr is not found by cmake. In the fallback implementation the constructor is missing which produces this exact error. Will be fixed shortly.

**Comment by Lachei** [comment]
> vsgXchange::openexr was missing implementation.

Should be fixed with 44b363a1d4354895467ff8b6f432ebf93000e0c3 .

Have you checked the assimp version for the other 2 issues?

**Comment by FarzanehBakhshaei** [comment]
My assimp version is 5.0. Even if cmake finds assimp, include directory of nlohmann_json is missing from VulkanPBRT project. As I mentioned before adding nlohmann_json to target_link_libraries of VulkanPBRT will fix this.

**Comment by Lachei** [comment]
Added nlohmann_json to the target link libraries in commit 684f7d32d541c25351ee0542940e89c695534952.
Do you still have the linking problems with assimp?
