### ISSUE TITLE
Debug configuration fails 

### ISSUE THREAD

**Issue by FarzanehBakhshaei** [Lachei/VulkanPBRT#29]
When I compile debug configuration I get the following 846 errors like below (Release configuration works fine):

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(ShaderLang.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(ShaderLang.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(PoolAlloc.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(PoolAlloc.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(Versions.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(Versions.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(Intermediate.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(Intermediate.obj)	1	
Error	LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(IntermTraverse.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in vsgconv.obj	vsgconv	C:\projects\VulkanPBRT\build\external\vsgXchange\applications\vsgconv\MachineIndependent.lib(IntermTraverse.obj)	1	
`

**Comment by Lachei** [comment]
This looks like the `vsgconv` is not being compiled in debug mode even though the rest of the project is.
As the vsgconv is never used you can quickly fix this error by uncommenting https://github.com/Lachei/VulkanPBRT/blob/0ab8dce075ddd37098ee2debc0d4e3f4d737b135/external/vsgXchange/CMakeLists.txt#L56.
I will look a bit more into detail later as this error is not critical and seems to be not general...
